services:
  # Database Service
  - type: pserv
    name: letrum-agency-db
    plan: starter

  # Backend Service  
  - type: web
    name: letrum-agency-backend
    env: node
    plan: starter
    rootDir: backend
    buildCommand: npm install && npm run build && npx prisma migrate deploy && npx prisma generate
    startCommand: npm run start:prod
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: letrum-agency-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: "7d"
      - key: PORT
        value: "10000"

  # Frontend Service
  - type: web
    name: letrum-agency-frontend
    env: node
    plan: starter
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          name: letrum-agency-backend
          type: web
          property: url
