services:
  # Backend Service  
  - type: web
    name: letrum-agency-backend
    env: node
    plan: starter
    rootDir: backend
    buildCommand: npm install && npm run build && npx prisma db push && npx prisma generate
    startCommand: npm run start:prod
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: "7d"
      - key: PORT
        value: "10000"

  # Frontend Service
  - type: web
    name: letrum-agency-frontend
    env: node
    plan: starter
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://letrum-agency-backend.onrender.com/api/v1
